apiVersion: v1
kind: Service
metadata:
  name: developer-iq-app-service-be
spec:
  selector:
    app: developer-iq-app
  type: NodePort
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30000